/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Mon Oct 28 21:26:56 2019. */

#include "cheese.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t cheese_Frame_fields[2] = {
    PB_FIELD(  3, INT32   , REPEATED, CALLBACK, FIRST, cheese_Frame, pixels, pixels, 0),
    PB_LAST_FIELD
};

const pb_field_t cheese_Pattern_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, cheese_Pattern, width, width, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, cheese_Pattern, height, width, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, cheese_Pattern, frames_per_beat, height, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, cheese_Pattern, unique_cycles, frames_per_beat, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, CALLBACK, OTHER, cheese_Pattern, frames, unique_cycles, &cheese_Frame_fields),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
